### PR TITLE
Edits

### PR DESCRIPTION
**Pull request by jzangeles**

### CODE REVIEW

**Comment by randal-sean-harrison** [comment]
Hi,
I think you're pushing to a forked repo for the template itself. I think what you wanted to do was to have cloned the repo and made your own changes and pushed up to your own repo. From your profile, it looks like you might be new to github. If you'd like, I'd be happy to walk you through how to do what I think you're trying to do. I teach this stuff at Notre Dame in my capacity as a technologies librarian, and am happy to help with this. 

You can find me at randalseanharrison.com and book us an appointment if this would be useful.

**Comment by jzangeles** [comment]
I'm very sorry. Yes, I am new to GitHub. I did not know that I was pushing changes on the template itself. I thought that forking the repository would create a copy which no longer affects the original. I hope I have not tampered anything in the original code. How do I undo the pushing of the forked repository? Again, I sincerely apologize.

**Comment by randal-sean-harrison** [comment]
Oh, it's no problem. I just won't pull/merge the changes into the codebase. All you'd want to do is re-download it "cloning" it instead of forking it and you should be good.

**Comment by jzangeles** [comment]
Oh thank you for the tip!

**Pull request closed without merging**
